In [8]:
import numpy as np

A_1d = np.arange(1, 11)
print(A_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:

A_2d = np.arange(1, 13).reshape(4, 3)
print(A_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
A_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]])
print(A_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
